# Generated by Django 4.2.5 on 2023-12-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='admins',
        ),
    ]
