# Generated by Django 4.2.5 on 2024-01-08 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0002_rename_admin_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='place',
        ),
    ]
